services:
  redis:
    image: "redis:7.0-alpine"
    container_name: backend_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        daphne -b 0.0.0.0 -p 8000 backend.asgi:application
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DEBUG=1
    restart: unless-stopped

volumes:
  redis_data: