# Generated by Django 5.2.1 on 2025-06-02 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(verbose_name='Duration in seconds')),
                ('number_of_participants', models.IntegerField(verbose_name='Number of participants')),
                ('title', models.CharField(max_length=255, verbose_name='Title of the decision')),
                ('context', models.TextField(verbose_name='Additional context')),
                ('current_step', models.IntegerField(choices=[(1, 'Step 1'), (2, 'Step 2'), (3, 'Step 3'), (4, 'Step 4'), (5, 'Step 5')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Proposal Description')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.decision')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PR', 'pro'), ('CO', 'con')], default='PR', max_length=2, verbose_name='Vote Type')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.proposal')),
            ],
        ),
    ]
